### ISSUE TITLE
docker-compose fails with type must be string for COLLECTOR_OTLP_ENABLED

### ISSUE THREAD

**Issue by forcollab** [habmic/opentelemetry-101#5]
docker-compose fails with type must be string for COLLECTOR_OTLP_ENABLED.

the docker-compose.yml has the below line which is causing the issue : 
COLLECTOR_OTLP_ENABLED: true

Adding quotes has resolved the issue.
COLLECTOR_OTLP_ENABLED: "True"

**Comment by habmic** [comment]
I released a fix, use the new tags (11-v2 and 12-v2)
