### ISSUE TITLE
opentelemetry-101_collector_1 exited with code 1

### ISSUE THREAD

**Issue by forcollab** [habmic/opentelemetry-101#6]
opentelemetry-101_collector_1 exited with code 1

Logs : 
`collector_1   | Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
collector_1   | 
collector_1   | * error decoding 'exporters': unknown type: "jaeger" for id: "jaeger" (valid values: [pulsar signalfx alibabacloud_logservice awscloudwatchlogs awsxray datadog googlecloudpubsub instana awsemf elasticsearch file logicmonitor skywalking f5cloud mezmo sapm syslog tanzuobservability debug logging dataset logzio opencensus splunk_hec dynatrace influxdb otlp otlphttp awskinesis awss3 azuremonitor coralogix kafka loadbalancing loki prometheusremotewrite azuredataexplorer carbon clickhouse googlecloud tencentcloud_logservice zipkin cassandra googlemanagedprometheus honeycombmarker prometheus sentry sumologic])
collector_1   | 2023/12/07 13:16:22 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
collector_1   | 
collector_1   | * error decoding 'exporters': unknown type: "jaeger" for id: "jaeger" (valid values: [pulsar signalfx alibabacloud_logservice awscloudwatchlogs awsxray datadog googlecloudpubsub instana awsemf elasticsearch file logicmonitor skywalking f5cloud mezmo sapm syslog tanzuobservability debug logging dataset logzio opencensus splunk_hec dynatrace influxdb otlp otlphttp awskinesis awss3 azuremonitor coralogix kafka loadbalancing loki prometheusremotewrite azuredataexplorer carbon clickhouse googlecloud tencentcloud_logservice zipkin cassandra googlemanagedprometheus honeycombmarker prometheus sentry sumologic])
opentelemetry-101_collector_1 exited with code 1
todo_1        | {"stack":"Error: PeriodicExportingMetricReader: metrics export failed (error Error: getaddrinfo ENOTFOUND collector)\n    at doExport (/usr/src/app/node_modules/@opentelemetry/sdk-metrics/src/export/PeriodicExportingMetricReader.ts:124:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at PeriodicExportingMetricReader._doRun (/usr/src/app/node_modules/@opentelemetry/sdk-metrics/src/export/PeriodicExportingMetricReader.ts:138:7)\n    at PeriodicExportingMetricReader._runOnce (/usr/src/app/node_modules/@opentelemetry/sdk-metrics/src/export/PeriodicExportingMetricReader.ts:95:7)","message":"PeriodicExportingMetricReader: metrics export failed (error Error: getaddrinfo ENOTFOUND collector)","name":"Error"}
auth_1        | {"stack":"Error: PeriodicExportingMetricReader: metrics export failed (error Error: getaddrinfo ENOTFOUND collector)\n    at doExport (/usr/src/app/node_modules/@opentelemetry/sdk-metrics/src/export/PeriodicExportingMetricReader.ts:124:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at PeriodicExportingMetricReader._doRun (/usr/src/app/node_modules/@opentelemetry/sdk-metrics/src/export/PeriodicExportingMetricReader.ts:138:7)\n    at PeriodicExportingMetricReader._runOnce (/usr/src/app/node_modules/@opentelemetry/sdk-metrics/src/export/PeriodicExportingMetricReader.ts:95:7)","message":"PeriodicExportingMetricReader: metrics export failed (error Error: getaddrinfo ENOTFOUND collector)","name":"Error"}`

**Comment by forcollab** [comment]
Seems Jaeger exported is depreciated now.

https://github.com/blueswen/fastapi-jaeger/issues/5 

Any workarounds ?

**Comment by habmic** [comment]
Yes, you can use the OTLP exporter to send directly Jaeger

**Comment by dtherhtun** [comment]
I used OTLP exporter but I got this error. 
```
opentelemetry-101-collector-1   | 2024-01-09T07:05:22.281Z      error   exporterhelper/queued_retry.go:391      Exporting failed. The error is not retryable. Dropping data.      {"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "Permanent error: rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.trace.v1.TraceService", "dropped_items": 7}
opentelemetry-101-collector-1   | go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
opentelemetry-101-collector-1   |       go.opentelemetry.io/collector/exporter@v0.80.0/exporterhelper/queued_retry.go:391
opentelemetry-101-collector-1   | go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
opentelemetry-101-collector-1   |       go.opentelemetry.io/collector/exporter@v0.80.0/exporterhelper/traces.go:126
opentelemetry-101-collector-1   | go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
opentelemetry-101-collector-1   |       go.opentelemetry.io/collector/exporter@v0.80.0/exporterhelper/queued_retry.go:195
opentelemetry-101-collector-1   | go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
opentelemetry-101-collector-1   |       go.opentelemetry.io/collector/exporter@v0.80.0/exporterhelper/internal/bounded_memory_queue.go:47
```

**Comment by john-forrest** [comment]
See https://opentelemetry.io/blog/2023/jaeger-exporter-collector-migration/

**Comment by habmic** [comment]
I released a fix, use the new tags (11-v2 and 12-v2)
